remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Investigation on the Relationship Between Cooking Time and Amount of Calories]
description: [Authors: Michelle Chen & Selina Han]
